melspec_config:
  clamp: 1.0e-05
  fmax: 16000
  fmin: 40
  hop_length: 512
  n_fft: 2048
  n_mels: 128
  sample_rate: 44100
  scale_factor: 4
  win_length: 1024
model_config:
  channels_scaleup_factor: 1.5
  down_sampling_factor: 3
  down_sampling_times: 7
  hidden_dims: 128
vocab:
  SP: 0
  K: 1
  L: 2
  M: 3
  N: 4
  NG: 5
  P: 6
  T: 7
  a: 8
  ae: 9
  b: 10
  bb: 11
  ch: 12
  d: 13
  dd: 14
  e: 15
  eo: 16
  eu: 17
  g: 18
  gg: 19
  h: 20
  i: 21
  j: 22
  jj: 23
  k: 24
  m: 25
  n: 26
  o: 27
  oe: 28
  p: 29
  r: 30
  s: 31
  ss: 32
  t: 33
  u: 34
  ui: 35
  wa: 36
  wae: 37
  we: 38
  wi: 39
  wo: 40
  ya: 41
  yae: 42
  ye: 43
  yeo: 44
  yo: 45
  yu: 46
  0: SP
  1: K
  2: L
  3: M
  4: N
  5: NG
  6: P
  7: T
  8: a
  9: ae
  10: b
  11: bb
  12: ch
  13: d
  14: dd
  15: e
  16: eo
  17: eu
  18: g
  19: gg
  20: h
  21: i
  22: j
  23: jj
  24: k
  25: m
  26: n
  27: o
  28: oe
  29: p
  30: r
  31: s
  32: ss
  33: t
  34: u
  35: ui
  36: wa
  37: wae
  38: we
  39: wi
  40: wo
  41: ya
  42: yae
  43: ye
  44: yeo
  45: yo
  46: yu
  AP: 0
  ? ''
  : 0
  <vocab_size>: 47
